import { getSqlite } from "./index";

const STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS firms (id text PRIMARY KEY, name text NOT NULL, legal_name text NOT NULL, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS legal_entities (id text PRIMARY KEY, firm_id text NOT NULL REFERENCES firms(id), name text NOT NULL, legal_name text NOT NULL, kind text NOT NULL, currency text NOT NULL, parent_entity_id text, inception_date text, end_date text, strategy_template text, vehicle_structure text, evergreen integer NOT NULL DEFAULT 0, no_construction integer NOT NULL DEFAULT 0, commitments text NOT NULL DEFAULT '0', gp_commitment text NOT NULL DEFAULT '0', call_cadence text, status text NOT NULL DEFAULT 'active', version integer NOT NULL DEFAULT 1, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS users (id text PRIMARY KEY, email text NOT NULL UNIQUE, display_name text NOT NULL, persona text NOT NULL, firm_id text REFERENCES firms(id), investor_id text, company_id text, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS memberships (id text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id), firm_id text NOT NULL REFERENCES firms(id), role text NOT NULL, entity_scope_json text)`,
  `CREATE TABLE IF NOT EXISTS disclosure_policies (id text PRIMARY KEY, firm_id text NOT NULL REFERENCES firms(id), name text NOT NULL, cutoff_date text, hide_other_lp_returns integer NOT NULL DEFAULT 1, visible_tabs_json text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS demo_settings (id text PRIMARY KEY, demo_clock text NOT NULL, warehouse_refreshed_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS companies (id text PRIMARY KEY, firm_id text NOT NULL REFERENCES firms(id), name text NOT NULL, legal_name text NOT NULL, sector text, stage text, website text, country text, status text NOT NULL DEFAULT 'active', created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS contacts (id text PRIMARY KEY, firm_id text NOT NULL REFERENCES firms(id), company_id text, investor_id text, name text NOT NULL, email text, title text, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS investors (id text PRIMARY KEY, firm_id text NOT NULL REFERENCES firms(id), name text NOT NULL, legal_name text NOT NULL, type text NOT NULL, country text, relationship_owner_id text, fundraising_stage text, bank_details_confirmed integer NOT NULL DEFAULT 0, bank_account_last4 text, disclosure_policy_id text, kyc_status text NOT NULL DEFAULT 'not_started', created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS deals (id text PRIMARY KEY, firm_id text NOT NULL REFERENCES firms(id), company_id text NOT NULL REFERENCES companies(id), name text NOT NULL, stage text NOT NULL, source text, adviser text, owner_id text, amount text, currency text NOT NULL DEFAULT 'USD', next_step text, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS interactions (id text PRIMARY KEY, firm_id text NOT NULL REFERENCES firms(id), company_id text, investor_id text, deal_id text, kind text NOT NULL, subject text NOT NULL, body text NOT NULL, occurred_at text NOT NULL, source_provenance text NOT NULL DEFAULT 'manual')`,
  `CREATE TABLE IF NOT EXISTS construction_configs (id text PRIMARY KEY, fund_id text NOT NULL REFERENCES legal_entities(id), version integer NOT NULL DEFAULT 1, name text NOT NULL, currency text NOT NULL, inception_date text NOT NULL, end_date text, commitments text NOT NULL, gp_commitment text NOT NULL, call_cadence text, vehicle_structure text, evergreen integer NOT NULL DEFAULT 0, no_construction integer NOT NULL DEFAULT 0, forecast_horizon_months integer NOT NULL DEFAULT 120, status text NOT NULL DEFAULT 'draft', updated_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS sector_profiles (id text PRIMARY KEY, construction_id text NOT NULL REFERENCES construction_configs(id), name text NOT NULL, sort_order integer NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS sector_stages (id text PRIMARY KEY, profile_id text NOT NULL REFERENCES sector_profiles(id), name text NOT NULL, sort_order integer NOT NULL, graduation text NOT NULL, exit text NOT NULL, months_to_next integer NOT NULL, months_to_exit integer NOT NULL, round_size text NOT NULL, pre_money text NOT NULL, post_money text NOT NULL, option_pool_dilution text NOT NULL, exit_value text NOT NULL, follow_on_check text NOT NULL DEFAULT '0')`,
  `CREATE TABLE IF NOT EXISTS allocations (id text PRIMARY KEY, construction_id text NOT NULL REFERENCES construction_configs(id), profile_id text NOT NULL REFERENCES sector_profiles(id), name text NOT NULL, entry_stage_id text NOT NULL, budget text NOT NULL, initial_check text NOT NULL, initial_ownership text NOT NULL, follow_on_amount text NOT NULL, follow_on_ownership text NOT NULL, follow_on_participation integer NOT NULL DEFAULT 1, horizon_months integer NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS fee_profiles (id text PRIMARY KEY, construction_id text NOT NULL REFERENCES construction_configs(id), name text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS fee_tiers (id text PRIMARY KEY, fee_profile_id text NOT NULL REFERENCES fee_profiles(id), start_date text NOT NULL, end_date text, rate text NOT NULL, basis text NOT NULL, fee_recycling integer NOT NULL DEFAULT 0)`,
  `CREATE TABLE IF NOT EXISTS expense_schedules (id text PRIMARY KEY, construction_id text NOT NULL REFERENCES construction_configs(id), name text NOT NULL, monthly_amount text NOT NULL, start_date text NOT NULL, end_date text)`,
  `CREATE TABLE IF NOT EXISTS recycling_policies (id text PRIMARY KEY, construction_id text NOT NULL REFERENCES construction_configs(id), recyclable_pct text NOT NULL, cap_vs_commitments text NOT NULL, term_months integer NOT NULL, use_anticipated_proceeds integer NOT NULL DEFAULT 0, fee_recycling_cap text NOT NULL DEFAULT '0')`,
  `CREATE TABLE IF NOT EXISTS fund_waterfall_configs (id text PRIMARY KEY, construction_id text NOT NULL REFERENCES construction_configs(id), structure text NOT NULL, preferred_rate text NOT NULL, catch_up integer NOT NULL DEFAULT 1, carry_rate text NOT NULL, profile text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS modeled_lps (id text PRIMARY KEY, construction_id text NOT NULL REFERENCES construction_configs(id), name text NOT NULL, commitment text NOT NULL, fee_profile_id text, custom_split_json text, investor_id text)`,
  `CREATE TABLE IF NOT EXISTS investments (id text PRIMARY KEY, fund_id text NOT NULL REFERENCES legal_entities(id), company_id text, portfolio_fund_id text, name text NOT NULL, status text NOT NULL, currency text NOT NULL, entry_stage_id text, profile_id text, fof_source_forecast text, fof_amount text, version integer NOT NULL DEFAULT 1, created_at text NOT NULL, updated_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS investment_cases (id text PRIMARY KEY, investment_id text NOT NULL REFERENCES investments(id), name text NOT NULL, probability text NOT NULL, is_base integer NOT NULL DEFAULT 0, cloned_from_id text)`,
  `CREATE TABLE IF NOT EXISTS investment_events (id text PRIMARY KEY, case_id text NOT NULL REFERENCES investment_cases(id), kind text NOT NULL, date text NOT NULL, amount text NOT NULL DEFAULT '0', ownership text, pre_money text, post_money text, round_currency text, fx_rate text, fx_rate_date text, security_type text, valuation_cap text, converted_ownership text, is_projected integer NOT NULL DEFAULT 0, source_provenance text NOT NULL DEFAULT 'manual', source_record_id text, notes text)`,
  `CREATE TABLE IF NOT EXISTS investment_liq_prefs (id text PRIMARY KEY, case_id text NOT NULL REFERENCES investment_cases(id), name text NOT NULL, seniority integer NOT NULL, type text NOT NULL, preference_amount text NOT NULL, participation_cap text, fully_diluted_ownership text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS fund_scenarios (id text PRIMARY KEY, fund_id text NOT NULL REFERENCES legal_entities(id), name text NOT NULL, status text NOT NULL DEFAULT 'draft', overrides_json text NOT NULL, result_json text, input_version integer NOT NULL, calculated_input_version integer, stale integer NOT NULL DEFAULT 1, created_at text NOT NULL, updated_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS monthly_actual_overrides (id text PRIMARY KEY, fund_id text NOT NULL REFERENCES legal_entities(id), month text NOT NULL, field text NOT NULL, amount text NOT NULL, updated_at text NOT NULL, UNIQUE(fund_id, month, field))`,
  `CREATE TABLE IF NOT EXISTS saved_views (id text PRIMARY KEY, firm_id text NOT NULL REFERENCES firms(id), user_id text, name text NOT NULL, surface text NOT NULL, columns_json text NOT NULL, filters_json text)`,
  `CREATE TABLE IF NOT EXISTS kpi_definitions (id text PRIMARY KEY, company_id text NOT NULL REFERENCES companies(id), name text NOT NULL, kind text NOT NULL, cadence text NOT NULL, unit text)`,
  `CREATE TABLE IF NOT EXISTS kpi_values (id text PRIMARY KEY, definition_id text NOT NULL REFERENCES kpi_definitions(id), period text NOT NULL, value text, qualitative text, status text NOT NULL, provenance text NOT NULL, accepted_at text)`,
  `CREATE TABLE IF NOT EXISTS kpi_requests (id text PRIMARY KEY, company_id text NOT NULL REFERENCES companies(id), period text NOT NULL, auto_approve integer NOT NULL DEFAULT 0, token text NOT NULL UNIQUE, status text NOT NULL, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS kpi_submissions (id text PRIMARY KEY, request_id text NOT NULL REFERENCES kpi_requests(id), definition_id text NOT NULL REFERENCES kpi_definitions(id), proposed_value text, prior_value text, status text NOT NULL, submitted_at text NOT NULL, reviewed_at text)`,
  `CREATE TABLE IF NOT EXISTS formulas (id text PRIMARY KEY, fund_id text NOT NULL REFERENCES legal_entities(id), name text NOT NULL, expression text NOT NULL, variables_json text NOT NULL, output_type text NOT NULL, updated_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS documents (id text PRIMARY KEY, firm_id text NOT NULL REFERENCES firms(id), name text NOT NULL, category text NOT NULL, mime_type text NOT NULL, storage_path text NOT NULL, related_type text, related_id text, watermark text, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS published_snapshots (id text PRIMARY KEY, fund_id text NOT NULL REFERENCES legal_entities(id), token text NOT NULL UNIQUE, payload_json text NOT NULL, investor_id text, revoked_at text, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS collaborators (id text PRIMARY KEY, fund_id text NOT NULL REFERENCES legal_entities(id), email text NOT NULL, permission text NOT NULL, section text NOT NULL, status text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS multi_fund_views (id text PRIMARY KEY, firm_id text NOT NULL REFERENCES firms(id), name text NOT NULL, fund_ids_json text NOT NULL, currency text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS integration_batches (id text PRIMARY KEY, firm_id text NOT NULL REFERENCES firms(id), kind text NOT NULL, status text NOT NULL, source text NOT NULL, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS integration_records (id text PRIMARY KEY, batch_id text NOT NULL REFERENCES integration_batches(id), source_record_id text NOT NULL, payload_json text NOT NULL, decision text NOT NULL DEFAULT 'pending', target_id text)`,
  `CREATE TABLE IF NOT EXISTS commitments (id text PRIMARY KEY, fund_id text NOT NULL REFERENCES legal_entities(id), investor_id text NOT NULL REFERENCES investors(id), amount text NOT NULL, currency text NOT NULL, status text NOT NULL, closing_id text, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS closings (id text PRIMARY KEY, fund_id text NOT NULL REFERENCES legal_entities(id), investor_id text NOT NULL REFERENCES investors(id), status text NOT NULL, target_amount text, soft_commitment text, legal_commitment text, questionnaire_status text, signature_simulated_at text, countersigned_at text, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS capital_activities (id text PRIMARY KEY, fund_id text NOT NULL REFERENCES legal_entities(id), kind text NOT NULL, status text NOT NULL, amount text NOT NULL, notice_date text NOT NULL, effective_date text NOT NULL, due_date text NOT NULL, memo text, version integer NOT NULL DEFAULT 1, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS capital_allocations (id text PRIMARY KEY, activity_id text NOT NULL REFERENCES capital_activities(id), investor_id text NOT NULL REFERENCES investors(id), amount text NOT NULL, received_amount text NOT NULL DEFAULT '0')`,
  `CREATE TABLE IF NOT EXISTS cash_receipts (id text PRIMARY KEY, activity_id text NOT NULL REFERENCES capital_activities(id), investor_id text NOT NULL REFERENCES investors(id), amount text NOT NULL, received_date text NOT NULL, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS journal_entries (id text PRIMARY KEY, entity_id text NOT NULL REFERENCES legal_entities(id), date text NOT NULL, effective_date text NOT NULL, memo text NOT NULL, source_type text NOT NULL, source_id text NOT NULL, status text NOT NULL, reversal_of_id text, currency text NOT NULL, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS journal_lines (id text PRIMARY KEY, entry_id text NOT NULL REFERENCES journal_entries(id), account_code text NOT NULL, account_name text NOT NULL, debit text NOT NULL DEFAULT '0', credit text NOT NULL DEFAULT '0', currency text NOT NULL, counterparty_entity_id text)`,
  `CREATE TABLE IF NOT EXISTS valuations (id text PRIMARY KEY, company_id text NOT NULL REFERENCES companies(id), fund_id text REFERENCES legal_entities(id), as_of_date text NOT NULL, status text NOT NULL, methods_json text NOT NULL, equity_value text, fund_nav_impact text, posted_journal_id text, posted_at text, version integer NOT NULL DEFAULT 1, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS collection_requests (id text PRIMARY KEY, company_id text NOT NULL REFERENCES companies(id), period text NOT NULL, currency text NOT NULL, cadence text NOT NULL, token text NOT NULL UNIQUE, status text NOT NULL, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS collection_answers (id text PRIMARY KEY, request_id text NOT NULL REFERENCES collection_requests(id), question text NOT NULL, value text, source_line text, status text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS waterfall_models (id text PRIMARY KEY, firm_id text NOT NULL REFERENCES firms(id), name text NOT NULL, nodes_json text NOT NULL, edges_json text NOT NULL, last_run_json text, last_run_input_hash text, stale integer NOT NULL DEFAULT 1, updated_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS gp_carry_units (id text PRIMARY KEY, gp_entity_id text NOT NULL REFERENCES legal_entities(id), member_name text NOT NULL, units text NOT NULL, vesting_start text NOT NULL, vesting_months integer NOT NULL, cliff_months integer NOT NULL DEFAULT 0)`,
  `CREATE TABLE IF NOT EXISTS distributions (id text PRIMARY KEY, fund_id text NOT NULL REFERENCES legal_entities(id), waterfall_run_id text, amount text NOT NULL, status text NOT NULL, requested_at text NOT NULL, approved_at text, memo text)`,
  `CREATE TABLE IF NOT EXISTS distribution_payments (id text PRIMARY KEY, distribution_id text NOT NULL REFERENCES distributions(id), investor_id text NOT NULL REFERENCES investors(id), amount text NOT NULL, bank_confirmed integer NOT NULL, status text NOT NULL, simulated_payment_ref text, journal_id text)`,
  `CREATE TABLE IF NOT EXISTS expenses (id text PRIMARY KEY, entity_id text NOT NULL REFERENCES legal_entities(id), vendor text NOT NULL, amount text NOT NULL, currency text NOT NULL, date text NOT NULL, category text NOT NULL, source text NOT NULL, receipt_document_id text)`,
  `CREATE TABLE IF NOT EXISTS expense_allocations (id text PRIMARY KEY, expense_id text NOT NULL REFERENCES expenses(id), entity_id text NOT NULL REFERENCES legal_entities(id), amount text NOT NULL, journal_id text)`,
  `CREATE TABLE IF NOT EXISTS tax_years (id text PRIMARY KEY, entity_id text NOT NULL REFERENCES legal_entities(id), year integer NOT NULL, status text NOT NULL, estimate_document_id text, final_document_id text)`,
  `CREATE TABLE IF NOT EXISTS tax_tasks (id text PRIMARY KEY, tax_year_id text NOT NULL REFERENCES tax_years(id), title text NOT NULL, status text NOT NULL, kind text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS audit_engagements (id text PRIMARY KEY, entity_id text NOT NULL REFERENCES legal_entities(id), year integer NOT NULL, status text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS audit_evidence (id text PRIMARY KEY, engagement_id text NOT NULL REFERENCES audit_engagements(id), category text NOT NULL, document_id text, related_type text, related_id text, status text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS kyc_cases (id text PRIMARY KEY, investor_id text NOT NULL REFERENCES investors(id), status text NOT NULL, screening_result text, reviewer_notes text, flagged integer NOT NULL DEFAULT 0, report_json text, updated_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS spv_formations (id text PRIMARY KEY, entity_id text NOT NULL REFERENCES legal_entities(id), status text NOT NULL, checklist_json text NOT NULL, updated_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS allocator_holdings (id text PRIMARY KEY, allocator_firm text NOT NULL, manager_name text NOT NULL, vehicle_name text NOT NULL, commitment text NOT NULL, paid_in text NOT NULL, distributions text NOT NULL, residual text NOT NULL, vintage integer NOT NULL, strategy text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS loans (id text PRIMARY KEY, firm_id text NOT NULL REFERENCES firms(id), name text NOT NULL, borrower text NOT NULL, principal text NOT NULL, outstanding text NOT NULL, annual_rate text NOT NULL, day_count text NOT NULL, start_date text NOT NULL, status text NOT NULL, pik integer NOT NULL DEFAULT 0)`,
  `CREATE TABLE IF NOT EXISTS loan_events (id text PRIMARY KEY, loan_id text NOT NULL REFERENCES loans(id), kind text NOT NULL, date text NOT NULL, amount text NOT NULL, note text)`,
  `CREATE TABLE IF NOT EXISTS saved_queries (id text PRIMARY KEY, firm_id text NOT NULL REFERENCES firms(id), name text NOT NULL, dataset text NOT NULL, filters_json text NOT NULL, group_by text, aggregate text NOT NULL, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS outbox_messages (id text PRIMARY KEY, kind text NOT NULL, to_address text NOT NULL, subject text NOT NULL, body text NOT NULL, status text NOT NULL, simulated integer NOT NULL DEFAULT 1, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS audit_log (id text PRIMARY KEY, firm_id text, actor_user_id text, action text NOT NULL, entity_type text NOT NULL, entity_id text NOT NULL, details_json text, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS sessions (id text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id), created_at text NOT NULL, expires_at text NOT NULL)`,
];

export function migrate() {
  const sqlite = getSqlite();
  sqlite.exec("BEGIN");
  try {
    for (const statement of STATEMENTS) sqlite.exec(statement);
    sqlite.exec("COMMIT");
  } catch (error) {
    sqlite.exec("ROLLBACK");
    throw error;
  }
}
